### ISSUE TITLE
Daughterboard Gerber files?

### ISSUE THREAD

**Issue by MrLightningBolt** [KS10FPGA/KS10FPGA#22]
I've been following development for a while and I was wanting to assemble the daughterboard. I've seen the photos and the schematic PDFs but I was wondering if you had Gerber files for PCB fabrication? Thanks!

**Comment by jfcl** [comment]
I don't have Gerber files.

I've accumulated all of the relevant design information and added a new section to the WIKI.  See:

https://github.com/KS10FPGA/KS10FPGA/wiki/Hardware#schematic-and-pwb-layout-design-information

I did try to contact you directly via email.

**Comment by MrLightningBolt** [comment]
This is fantastic, thank you very much!
